### PR TITLE
bump kind to 0.16.0

### LINKED ISSUE #4: Update KinD action consuming KinD 0.16.0
## Please describe what you would like to see in this project

Update KinD action consuming KinD 0.16.0

### PR DESCRIPTION
**Pull request by sandrobonazzola**
## Changes introduced with this PR

bump kind to 0.16.0

Fixes #4 

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
@sandrobonazzola we don't have a CI here, which is an oversight. Did you manage to test this upgrade?

**Comment by sandrobonazzola** [comment]
KinD 0.16.0 works for me ; I haven't tried the action itself.

**Comment by ghost** [comment]
Feel free to merge, but we need to add a test here, it would be nasty if an upgrade broke the KinD setup.

**Comment by sandrobonazzola** [comment]
I'll add CI before merging this one

**Review by ghost — APPROVED** [review]

**Pull request merged**
